-- One-time import: Aichi-Nagoya 2026 Athletics players (photos already uploaded to S3).
-- Looks up the edition by name pattern rather than a hardcoded id, since local dev
-- and production edition ids/slugs have diverged (production has more editions,
-- and this one was renamed there, which regenerated its slug).
BEGIN;
DO $$
DECLARE target_id INT;
BEGIN
  SELECT id INTO target_id FROM game_editions WHERE name LIKE '%Aichi-Nagoya%2026%';
  IF target_id IS NULL THEN RAISE EXCEPTION 'Could not find the Aichi-Nagoya 2026 edition — check game_editions.name manually'; END IF;
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Abbas Yusuf Abbas Ali', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/2471da43-8344-4fca-ba83-33181b97bdc1.jpg', 1);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Abdelrahman Mahmoud E. Mahmoud', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/5bed0f47-b698-455f-aa1f-02cd4d9d1c8d.jpg', 2);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Abdikani Mohamed A. Hamid', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/316cc01f-8ea7-41cd-9674-3fe957631370.jpg', 3);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Abdisamad Said S. Hirsi', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/bfe916be-37f8-4da3-ae84-eb1ae8d0299c.png', 4);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Abdulraof Oriade Rashed', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/945aa419-d6b9-4720-b41d-3a24f95777b7.jpg', 5);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Ahmed Sabri Ahmed Mohamed Mohamoud', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/e4462348-79ff-456b-903f-0715b219925b.png', 6);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Aisha Peace M. Abdullah', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/8cc52888-c4b4-49ff-83d8-9e93b4de90aa.png', 7);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Alaa Samuel A. Sami', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/3cb33b93-f028-487d-b162-f1fa7fbd7f9b.jpg', 8);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Albert Kibichii R . Kiptoo', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/6acd07a8-e768-4e54-8872-baee5afd33b8.jpg', 9);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Ali Mohamed Jasim Haider Haji', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/0ed9e830-04fa-4d41-8426-e2f43d9f08f1.jpg', 10);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Birhanu Yemataw Balew', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/5e17b42e-078a-4f18-9bc2-ab2916b8bc8e.jpg', 11);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Ebrahim Simon Abdallah Omar', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/3afea90c-6de2-41e7-a9cc-d24a358a70f1.jpg', 12);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Edidiong Ofonime Odiong', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/10be6735-6c66-4532-9a96-dee5842c86de.png', 13);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Elhassan Elalami Mohammed Elabbassi', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/ae99fab2-74e9-4061-8993-1650374b4f26.jpg', 14);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Hajar Saad Saeed Saad Sowaid Alameeri Alkhaldi', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/0e9f3de8-de1d-4f34-a933-d6e8bf816bc6.jpg', 15);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Hamse Bade M. Dhabar', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/c6f09bd7-d2ed-4a0c-882b-b658a6a44ef3.png', 16);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Layla Esther Salim Kamal', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/daecfd95-179f-49cf-aba4-cfdf25aaabdf.jpg', 17);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Musa Ali Musa Isah', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/7625a3f4-f7e1-490b-bd6b-e3e44ea2ff1b.png', 18);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Nelly Jepkosgei Rotich Korir', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/2add2c31-40ec-4879-b480-f989df3ddee5.jpg', 19);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Oluwakemi Mujidat Adekoya', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/fcd9d814-4b9f-405a-b623-012fd28f977a.jpg', 20);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Raihanah Anuoluwapo R. Garoubah', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/bd4cda77-c3cc-47b1-875d-102209793e60.jpg', 21);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Rose Chelimo Jonathan K. Sitienei', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/6c96b097-92fe-4327-a86f-91ed05e238fd.jpg', 22);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Ruth Danies Albert Jebet', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/8fb5e929-0652-4607-b051-e99a7aee1003.jpg', 23);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Salem Salem N. Bakheet', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/074631d5-c2a5-4ba5-bb41-41acc71fd132.jpg', 24);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Salwa Eid Naser Naser', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/b86efccd-1ecf-404b-991b-d379c374d03d.jpg', 25);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Shfian Hasmau M. Abdulghani', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/d79f577c-3fa6-45b9-bfc6-04e332647b17.png', 26);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Shitaye Eshete H. Habte', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/4c3061fe-c790-4050-8b00-08bb06479b18.png', 27);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Tigest Getent Mekone', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/0de2117c-c6ba-4e4f-8501-4c6d48745d9e.png', 28);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Winefred Mutile Yavi', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/60c884d3-d167-43a6-af22-15baadad7531.png', 29);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Zainab Ali M. Fyofuoba', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/f165f310-f3fe-4531-b2d5-41d85edc84c4.jpg', 30);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Zenab Moussa Ali Mahamat', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/ef74dcf7-f02c-44e6-bc80-b08aab1e00a0.jpg', 31);
  INSERT INTO game_edition_players (game_edition_id, name, sport, photo_path, sort_order) VALUES (target_id, 'Zouhair Aouad', 'Athletics', 'https://team-bahrain-uploads.s3.us-east-2.amazonaws.com/uploads/fede2db5-dbbc-443e-8c5c-b7866036b95b.jpg', 32);
END $$;
COMMIT;
